// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_txDetail.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ignoring public import of Coin from model_common.proto

// Ignoring public import of Address from model_common.proto

// Ignoring public import of Fee from model_common.proto

// Ignoring public import of Memo from model_common.proto

type TxDetailRequest struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=txHash" json:"txHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxDetailRequest) Reset()         { *m = TxDetailRequest{} }
func (m *TxDetailRequest) String() string { return proto.CompactTextString(m) }
func (*TxDetailRequest) ProtoMessage()    {}
func (*TxDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_txDetail_bb933201bc71927e, []int{0}
}
func (m *TxDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxDetailRequest.Unmarshal(m, b)
}
func (m *TxDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxDetailRequest.Marshal(b, m, deterministic)
}
func (dst *TxDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxDetailRequest.Merge(dst, src)
}
func (m *TxDetailRequest) XXX_Size() int {
	return xxx_messageInfo_TxDetailRequest.Size(m)
}
func (m *TxDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxDetailRequest proto.InternalMessageInfo

func (m *TxDetailRequest) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type TxDetailResponse struct {
	TxHash               string                `protobuf:"bytes,1,opt,name=txHash" json:"txHash,omitempty"`
	Time                 string                `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	Height               uint64                `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	From                 *Address              `protobuf:"bytes,4,opt,name=from" json:"from,omitempty"`
	To                   *Address              `protobuf:"bytes,5,opt,name=to" json:"to,omitempty"`
	Amount               []*Coin               `protobuf:"bytes,6,rep,name=amount" json:"amount,omitempty"`
	Type                 string                `protobuf:"bytes,7,opt,name=type" json:"type,omitempty"`
	Status               string                `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	Fee                  *TxDetailResponse_Fee `protobuf:"bytes,9,opt,name=fee" json:"fee,omitempty"`
	Memo                 *Memo                 `protobuf:"bytes,10,opt,name=memo" json:"memo,omitempty"`
	Ext                  []byte                `protobuf:"bytes,11,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TxDetailResponse) Reset()         { *m = TxDetailResponse{} }
func (m *TxDetailResponse) String() string { return proto.CompactTextString(m) }
func (*TxDetailResponse) ProtoMessage()    {}
func (*TxDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_txDetail_bb933201bc71927e, []int{1}
}
func (m *TxDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxDetailResponse.Unmarshal(m, b)
}
func (m *TxDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxDetailResponse.Marshal(b, m, deterministic)
}
func (dst *TxDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxDetailResponse.Merge(dst, src)
}
func (m *TxDetailResponse) XXX_Size() int {
	return xxx_messageInfo_TxDetailResponse.Size(m)
}
func (m *TxDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxDetailResponse proto.InternalMessageInfo

func (m *TxDetailResponse) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *TxDetailResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *TxDetailResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TxDetailResponse) GetFrom() *Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TxDetailResponse) GetTo() *Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TxDetailResponse) GetAmount() []*Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *TxDetailResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TxDetailResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TxDetailResponse) GetFee() *TxDetailResponse_Fee {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *TxDetailResponse) GetMemo() *Memo {
	if m != nil {
		return m.Memo
	}
	return nil
}

func (m *TxDetailResponse) GetExt() []byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

type TxDetailResponse_Fee struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom" json:"denom,omitempty"`
	Cost                 float64  `protobuf:"fixed64,2,opt,name=cost" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxDetailResponse_Fee) Reset()         { *m = TxDetailResponse_Fee{} }
func (m *TxDetailResponse_Fee) String() string { return proto.CompactTextString(m) }
func (*TxDetailResponse_Fee) ProtoMessage()    {}
func (*TxDetailResponse_Fee) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_txDetail_bb933201bc71927e, []int{1, 0}
}
func (m *TxDetailResponse_Fee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxDetailResponse_Fee.Unmarshal(m, b)
}
func (m *TxDetailResponse_Fee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxDetailResponse_Fee.Marshal(b, m, deterministic)
}
func (dst *TxDetailResponse_Fee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxDetailResponse_Fee.Merge(dst, src)
}
func (m *TxDetailResponse_Fee) XXX_Size() int {
	return xxx_messageInfo_TxDetailResponse_Fee.Size(m)
}
func (m *TxDetailResponse_Fee) XXX_DiscardUnknown() {
	xxx_messageInfo_TxDetailResponse_Fee.DiscardUnknown(m)
}

var xxx_messageInfo_TxDetailResponse_Fee proto.InternalMessageInfo

func (m *TxDetailResponse_Fee) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *TxDetailResponse_Fee) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func init() {
	proto.RegisterType((*TxDetailRequest)(nil), "model.txDetail.TxDetailRequest")
	proto.RegisterType((*TxDetailResponse)(nil), "model.txDetail.TxDetailResponse")
	proto.RegisterType((*TxDetailResponse_Fee)(nil), "model.txDetail.TxDetailResponse.Fee")
}

func init() {
	proto.RegisterFile("model_txDetail.proto", fileDescriptor_model_txDetail_bb933201bc71927e)
}

var fileDescriptor_model_txDetail_bb933201bc71927e = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x34, 0x69, 0xfa, 0x76, 0x2a, 0x5a, 0x96, 0x2a, 0x4b, 0x4f, 0xa1, 0xa8, 0xa4,
	0x1e, 0x22, 0x54, 0xf0, 0xee, 0x1f, 0x8a, 0x17, 0x41, 0x16, 0x4f, 0x5e, 0x24, 0x36, 0x53, 0x1b,
	0xe8, 0x66, 0x62, 0x77, 0x0a, 0xed, 0xe7, 0xf1, 0x8b, 0x4a, 0x26, 0x11, 0x69, 0x41, 0x6f, 0xf3,
	0xcc, 0xfc, 0x66, 0xf7, 0xd9, 0x67, 0x61, 0x60, 0x29, 0xc3, 0xe5, 0x2b, 0x6f, 0xee, 0x91, 0xd3,
	0x7c, 0x99, 0x94, 0x2b, 0x62, 0x52, 0x87, 0xd2, 0x4d, 0xbe, 0xbb, 0x43, 0x55, 0x53, 0x33, 0xb2,
	0x96, 0x8a, 0x9a, 0x19, 0x8d, 0xe1, 0xe8, 0xb9, 0x99, 0x1b, 0xfc, 0x58, 0xa3, 0x63, 0x75, 0x02,
	0x21, 0x6f, 0x1e, 0x52, 0xb7, 0xd0, 0x5e, 0xe4, 0xc5, 0x5d, 0xd3, 0xa8, 0xd1, 0xa7, 0x0f, 0xfd,
	0x1f, 0xd6, 0x95, 0x54, 0x38, 0xfc, 0x0d, 0x56, 0x0a, 0x02, 0xce, 0x2d, 0xea, 0x96, 0x74, 0xa5,
	0xae, 0xd8, 0x05, 0xe6, 0xef, 0x0b, 0xd6, 0x7e, 0xe4, 0xc5, 0x81, 0x69, 0x94, 0x1a, 0x43, 0x30,
	0x5f, 0x91, 0xd5, 0x41, 0xe4, 0xc5, 0xbd, 0xc9, 0x71, 0x52, 0xdb, 0x6e, 0x6c, 0xde, 0x64, 0xd9,
	0x0a, 0x9d, 0x33, 0x82, 0xa8, 0x33, 0x68, 0x31, 0xe9, 0xf6, 0x5f, 0x60, 0x8b, 0x49, 0x5d, 0x40,
	0x98, 0x5a, 0x5a, 0x17, 0xac, 0xc3, 0xc8, 0x8f, 0x7b, 0x13, 0xb5, 0x8b, 0xde, 0x51, 0x5e, 0x98,
	0x86, 0x10, 0xa7, 0xdb, 0x12, 0x75, 0xa7, 0x71, 0xba, 0x2d, 0xc5, 0xa9, 0xe3, 0x94, 0xd7, 0x4e,
	0xff, 0xaf, 0x5f, 0x55, 0x2b, 0x75, 0x0d, 0xfe, 0x1c, 0x51, 0x77, 0xe5, 0xfe, 0xd3, 0x64, 0x37,
	0xdf, 0x64, 0x3f, 0x9c, 0x64, 0x8a, 0x68, 0xaa, 0x05, 0x75, 0x0e, 0x81, 0x45, 0x4b, 0x1a, 0x64,
	0x71, 0xcf, 0xcd, 0x23, 0x5a, 0x32, 0x32, 0x57, 0x7d, 0xf0, 0x71, 0xc3, 0xba, 0x17, 0x79, 0xf1,
	0x81, 0xa9, 0xca, 0xe1, 0x25, 0xf8, 0x53, 0x44, 0x35, 0x80, 0x76, 0x86, 0x05, 0xd9, 0x26, 0xe5,
	0x5a, 0x54, 0xd6, 0x67, 0xe4, 0x58, 0x42, 0xf6, 0x8c, 0xd4, 0xb7, 0x9d, 0x97, 0xb6, 0x9c, 0xfe,
	0xf4, 0xef, 0x2d, 0x94, 0x2f, 0xbe, 0xfa, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x43, 0xaa, 0x0e,
	0x1e, 0x02, 0x00, 0x00,
}
