// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_txList.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ignoring public import of Coin from model_common.proto

// Ignoring public import of Address from model_common.proto

// Ignoring public import of Fee from model_common.proto

// Ignoring public import of Memo from model_common.proto

type TxListRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Page                 uint64   `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PerPage              uint64   `protobuf:"varint,3,opt,name=perPage" json:"perPage,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	StartTime            string   `protobuf:"bytes,6,opt,name=startTime" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,7,opt,name=endTime" json:"endTime,omitempty"`
	Sort                 string   `protobuf:"bytes,8,opt,name=sort" json:"sort,omitempty"`
	Q                    string   `protobuf:"bytes,9,opt,name=q" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxListRequest) Reset()         { *m = TxListRequest{} }
func (m *TxListRequest) String() string { return proto.CompactTextString(m) }
func (*TxListRequest) ProtoMessage()    {}
func (*TxListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_txList_89f6fed979daf4b9, []int{0}
}
func (m *TxListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxListRequest.Unmarshal(m, b)
}
func (m *TxListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxListRequest.Marshal(b, m, deterministic)
}
func (dst *TxListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxListRequest.Merge(dst, src)
}
func (m *TxListRequest) XXX_Size() int {
	return xxx_messageInfo_TxListRequest.Size(m)
}
func (m *TxListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxListRequest proto.InternalMessageInfo

func (m *TxListRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TxListRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *TxListRequest) GetPerPage() uint64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *TxListRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TxListRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TxListRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *TxListRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *TxListRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *TxListRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

type TxListResponse struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=txHash" json:"txHash,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	Height               uint64   `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	From                 *Address `protobuf:"bytes,4,opt,name=from" json:"from,omitempty"`
	To                   *Address `protobuf:"bytes,5,opt,name=to" json:"to,omitempty"`
	Amount               []*Coin  `protobuf:"bytes,6,rep,name=amount" json:"amount,omitempty"`
	Type                 string   `protobuf:"bytes,7,opt,name=type" json:"type,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	Ext                  string   `protobuf:"bytes,9,opt,name=ext" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxListResponse) Reset()         { *m = TxListResponse{} }
func (m *TxListResponse) String() string { return proto.CompactTextString(m) }
func (*TxListResponse) ProtoMessage()    {}
func (*TxListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_txList_89f6fed979daf4b9, []int{1}
}
func (m *TxListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxListResponse.Unmarshal(m, b)
}
func (m *TxListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxListResponse.Marshal(b, m, deterministic)
}
func (dst *TxListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxListResponse.Merge(dst, src)
}
func (m *TxListResponse) XXX_Size() int {
	return xxx_messageInfo_TxListResponse.Size(m)
}
func (m *TxListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxListResponse proto.InternalMessageInfo

func (m *TxListResponse) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *TxListResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *TxListResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TxListResponse) GetFrom() *Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TxListResponse) GetTo() *Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TxListResponse) GetAmount() []*Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *TxListResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TxListResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TxListResponse) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func init() {
	proto.RegisterType((*TxListRequest)(nil), "model.txList.TxListRequest")
	proto.RegisterType((*TxListResponse)(nil), "model.txList.TxListResponse")
}

func init() { proto.RegisterFile("model_txList.proto", fileDescriptor_model_txList_89f6fed979daf4b9) }

var fileDescriptor_model_txList_89f6fed979daf4b9 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xfd, 0x5a, 0x4a, 0x0b, 0x03, 0x9f, 0x31, 0x93, 0x48, 0x36, 0xc6, 0x03, 0x21, 0x31, 0x41,
	0x0f, 0x1c, 0xf0, 0x17, 0xa8, 0x17, 0x0f, 0x1e, 0x48, 0xc3, 0xc9, 0x8b, 0xa9, 0x76, 0x85, 0x26,
	0xb6, 0x53, 0x76, 0x87, 0x04, 0xff, 0x85, 0x7f, 0xd0, 0xff, 0x62, 0x76, 0x76, 0x11, 0x39, 0x78,
	0x9b, 0xf7, 0xf6, 0xe5, 0xcd, 0xbc, 0x97, 0x05, 0xac, 0xa9, 0xd4, 0xef, 0xcf, 0xbc, 0x7b, 0xac,
	0x2c, 0xcf, 0x5a, 0x43, 0x4c, 0x38, 0x14, 0x6e, 0xe6, 0xb9, 0xf3, 0xa0, 0x78, 0xa5, 0xba, 0xa6,
	0xc6, 0x2b, 0x26, 0x5f, 0x11, 0xfc, 0x5f, 0xca, 0x73, 0xae, 0x37, 0x5b, 0x6d, 0x19, 0x15, 0x64,
	0x45, 0x59, 0x1a, 0x6d, 0xad, 0x8a, 0xc6, 0xd1, 0xb4, 0x9f, 0xef, 0x21, 0x22, 0x24, 0x6d, 0xb1,
	0xd2, 0x2a, 0x1e, 0x47, 0xd3, 0x24, 0x97, 0xd9, 0xa9, 0x5b, 0x6d, 0x16, 0x8e, 0xee, 0x08, 0xbd,
	0x87, 0x38, 0x82, 0xd4, 0x72, 0xc1, 0x5b, 0xab, 0x12, 0xb1, 0x09, 0xc8, 0xb9, 0xf0, 0x47, 0xab,
	0x55, 0x57, 0x58, 0x99, 0xf1, 0x02, 0xfa, 0x96, 0x0b, 0xc3, 0xcb, 0xaa, 0xd6, 0x2a, 0x95, 0x87,
	0x03, 0xe1, 0x76, 0xe8, 0xa6, 0x94, 0xb7, 0xcc, 0x5f, 0x14, 0xa0, 0xf3, 0xb2, 0x64, 0x58, 0xf5,
	0xbc, 0x97, 0x9b, 0x71, 0x08, 0xd1, 0x46, 0xf5, 0x85, 0x88, 0x36, 0x93, 0xcf, 0x18, 0x4e, 0xf6,
	0xf9, 0x6c, 0x4b, 0x8d, 0x95, 0xc3, 0x78, 0xf7, 0x50, 0xd8, 0x75, 0xc8, 0x17, 0x90, 0x1c, 0xe6,
	0x76, 0xc4, 0xe1, 0x30, 0xb7, 0x60, 0x04, 0xe9, 0x5a, 0x57, 0xab, 0x35, 0x87, 0x74, 0x01, 0xe1,
	0x15, 0x24, 0x6f, 0x86, 0x6a, 0x89, 0x36, 0x98, 0x9f, 0xcd, 0x7c, 0xcf, 0xa1, 0xd9, 0x5b, 0xdf,
	0x57, 0x2e, 0x12, 0xbc, 0x84, 0x98, 0x49, 0xd2, 0xfe, 0x29, 0x8c, 0x99, 0xf0, 0x1a, 0xd2, 0xa2,
	0xa6, 0x6d, 0xc3, 0x2a, 0x1d, 0x77, 0xa6, 0x83, 0x39, 0x1e, 0x4b, 0xef, 0xa9, 0x6a, 0xf2, 0xa0,
	0xf8, 0xa9, 0x30, 0xfb, 0x55, 0xe1, 0xa1, 0xee, 0xde, 0x51, 0xdd, 0xa7, 0xd0, 0xd1, 0x3b, 0x0e,
	0x85, 0xb8, 0xf1, 0x2e, 0x7b, 0xea, 0x8a, 0xf5, 0xe2, 0xdf, 0x4b, 0x2a, 0x9f, 0xe0, 0xe6, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x9d, 0xb9, 0xe2, 0x88, 0x3c, 0x02, 0x00, 0x00,
}
